let title = 'Just project';
console.log(typeof title);
let screens = 'Простые, Сложные, Интерактивные';
console.log(screens.length);
let screenPrice = 50;
let rollback = 35;
let fullPrice = 85;
console.log(typeof fullPrice);
let adaptive = true;
console.log(typeof adaptive);